repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.20.0
  hooks:
  - id: pyupgrade
    args: [--py313-plus]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: fix-byte-order-marker
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-builtin-literals
  - id: check-toml
  - id: double-quote-string-fixer
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
  - id: python-check-blanket-type-ignore
  - id: python-check-mock-methods
  - id: python-no-eval
  - id: python-no-log-warn
  - id: python-use-type-annotations
  - id: text-unicode-replacement-char
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-no-eval
  - id: text-unicode-replacement-char
    exclude: .js$
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-implicit-str-concat
    args: [--max-line-length=100]
- repo: https://github.com/mrtazz/checkmake.git
  rev: 0.2.2
  hooks:
  - id: checkmake
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
    args: [--autofix, --indent, '2']
- repo: https://codeberg.org/frnmst/md-toc
  rev: 9.0.0
  hooks:
  - id: md-toc
    args: [-p, github]
